import Navigation from "../components/navigation";
import "../styles/global.css";

export const metadata = {
  title: {
    template: "💲%s💲"
  },
  description: "billionaire Generated by Next.js"
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <Navigation />
        </header>
        {children}
      </body>
    </html>
  )
}
